export enum FailureCode {
  DATA_EMPTY = "DATA_EMPTY",
  DATA_NOISE = "DATA_NOISE",
  MODEL_HALLUCINATION = "MODEL_HALLUCINATION",
  MODEL_OVERCONFIDENCE = "MODEL_OVERCONFIDENCE",
  INTEGRATION_FAILURE = "INTEGRATION_FAILURE",
  COST_OVERFLOW = "COST_OVERFLOW",
  OUTPUT_UNUSABLE = "OUTPUT_UNUSABLE",
}
