-- AlterEnum
ALTER TYPE "ResearchSource" ADD VALUE IF NOT EXISTS 'AMAZON_MAIN_PRODUCT';
ALTER TYPE "ResearchSource" ADD VALUE IF NOT EXISTS 'AMAZON_COMPETITOR_1';
ALTER TYPE "ResearchSource" ADD VALUE IF NOT EXISTS 'AMAZON_COMPETITOR_2';
ALTER TYPE "ResearchSource" ADD VALUE IF NOT EXISTS 'AMAZON_COMPETITOR_3';
